In [21]:
import pandas as pd

df_reviews_acura = pd.read_csv("../datasets/reviews/scraped_car_reviews_acura.csv", sep=",", header=0, lineterminator="\n")
df_reviews_alfaromeo = pd.read_csv("../datasets/reviews/scraped_car_reviews_alfaromeo.csv", sep=",", header=0, lineterminator="\n")
df_reviews_astonmartin = pd.read_csv("../datasets/reviews/scraped_car_reviews_astonmartin.csv", sep=",", header=0, lineterminator="\n")
df_reviews_audi = pd.read_csv("../datasets/reviews/scraped_car_reviews_audi.csv", sep=",", header=0, lineterminator="\n")
df_reviews_bentley = pd.read_csv("../datasets/reviews/scraped_car_reviews_bentley.csv", sep=",", header=0, lineterminator="\n")
df_reviews_bmw = pd.read_csv("../datasets/reviews/scraped_car_reviews_bmw.csv", sep=",", header=0, lineterminator="\n")
df_reviews_buick = pd.read_csv("../datasets/reviews/scraped_car_reviews_buick.csv", sep=",", header=0, lineterminator="\n")
df_reviews_cadillac = pd.read_csv("../datasets/reviews/scraped_car_reviews_cadillac.csv", sep=",", header=0, lineterminator="\n")
df_reviews_chevrolet = pd.read_csv("../datasets/reviews/scraped_car_reviews_chevrolet.csv", sep=",", header=0, lineterminator="\n")
df_reviews_chrysler = pd.read_csv("../datasets/reviews/scraped_car_reviews_chrysler.csv", sep=",", header=0, lineterminator="\n")
df_reviews_dodge = pd.read_csv("../datasets/reviews/scraped_car_reviews_dodge.csv", sep=",", header=0, lineterminator="\n")
df_reviews_ferrari = pd.read_csv("../datasets/reviews/scraped_car_reviews_ferrari.csv", sep=",", header=0, lineterminator="\n")
df_reviews_fiat = pd.read_csv("../datasets/reviews/scraped_car_reviews_fiat.csv", sep=",", header=0, lineterminator="\n")
df_reviews_ford = pd.read_csv("../datasets/reviews/scraped_car_reviews_ford.csv", sep=",", header=0, lineterminator="\n")
df_reviews_genesis = pd.read_csv("../datasets/reviews/scraped_car_reviews_genesis.csv", sep=",", header=0, lineterminator="\n")
df_reviews_gmc = pd.read_csv("../datasets/reviews/scraped_car_reviews_gmc.csv", sep=",", header=0, lineterminator="\n")
df_reviews_honda = pd.read_csv("../datasets/reviews/scraped_car_reviews_honda.csv", sep=",", header=0, lineterminator="\n")
df_reviews_hummer = pd.read_csv("../datasets/reviews/scraped_car_reviews_hummer.csv", sep=",", header=0, lineterminator="\n")
df_reviews_hyundai = pd.read_csv("../datasets/reviews/scraped_car_reviews_hyundai.csv", sep=",", header=0, lineterminator="\n")
df_reviews_infiniti = pd.read_csv("../datasets/reviews/scraped_car_reviews_infiniti.csv", sep=",", header=0, lineterminator="\n")
df_reviews_kia = pd.read_csv("../datasets/reviews/scraped_car_reviews_kia.csv", sep=",", header=0, lineterminator="\n")
df_reviews_lamborghini = pd.read_csv("../datasets/reviews/scraped_car_reviews_lamborghini.csv", sep=",", header=0, lineterminator="\n")
df_reviews_land_rover = pd.read_csv("../datasets/reviews/scraped_car_reviews_land-rover.csv", sep=",", header=0, lineterminator="\n")
df_reviews_lexus = pd.read_csv("../datasets/reviews/scraped_car_reviews_lexus.csv", sep=",", header=0, lineterminator="\n")
df_reviews_lincoln = pd.read_csv("../datasets/reviews/scraped_car_reviews_lincoln.csv", sep=",", header=0, lineterminator="\n")
df_reviews_lotus = pd.read_csv("../datasets/reviews/scraped_car_reviews_lotus.csv", sep=",", header=0, lineterminator="\n")
df_reviews_maserati = pd.read_csv("../datasets/reviews/scraped_car_reviews_maserati.csv", sep=",", header=0, lineterminator="\n")
df_reviews_maybach = pd.read_csv("../datasets/reviews/scraped_car_reviews_maybach.csv", sep=",", header=0, lineterminator="\n")
df_reviews_mazda = pd.read_csv("../datasets/reviews/scraped_car_reviews_mazda.csv", sep=",", header=0, lineterminator="\n")
df_reviews_mclaren = pd.read_csv("../datasets/reviews/scraped_car_reviews_mclaren.csv", sep=",", header=0, lineterminator="\n")
df_reviews_mercedes_benz = pd.read_csv("../datasets/reviews/scraped_car_reviews_mercedes-benz.csv", sep=",", header=0, lineterminator="\n")
df_reviews_mitsubishi = pd.read_csv("../datasets/reviews/scraped_car_reviews_mitsubishi.csv", sep=",", header=0, lineterminator="\n")
df_reviews_nissan = pd.read_csv("../datasets/reviews/scraped_car_reviews_nissan.csv", sep=",", header=0, lineterminator="\n")
df_reviews_pontiac = pd.read_csv("../datasets/reviews/scraped_car_reviews_pontiac.csv", sep=",", header=0, lineterminator="\n")
df_reviews_porsche = pd.read_csv("../datasets/reviews/scraped_car_reviews_porsche.csv", sep=",", header=0, lineterminator="\n")
df_reviews_rolls_royce = pd.read_csv("../datasets/reviews/scraped_car_reviews_rolls-royce.csv", sep=",", header=0, lineterminator="\n")
df_reviews_subaru = pd.read_csv("../datasets/reviews/scraped_car_reviews_subaru.csv", sep=",", header=0, lineterminator="\n")
df_reviews_suzuki = pd.read_csv("../datasets/reviews/scraped_car_reviews_suzuki.csv", sep=",", header=0, lineterminator="\n")
df_reviews_tesla = pd.read_csv("../datasets/reviews/scraped_car_reviews_tesla.csv", sep=",", header=0, lineterminator="\n")
df_reviews_toyota = pd.read_csv("../datasets/reviews/scraped_car_reviews_toyota.csv", sep=",", header=0, lineterminator="\n")
df_reviews_volkswagen = pd.read_csv("../datasets/reviews/scraped_car_reviews_volkswagen.csv", sep=",", header=0, lineterminator="\n")
df_reviews_volvo = pd.read_csv("../datasets/reviews/scraped_car_reviews_volvo.csv", sep=",", header=0, lineterminator="\n")

df_reviews_acura["Make"] = df_reviews_acura["Vehicle_Title"].str.split()[0][1]
df_reviews_alfaromeo["Make"] = df_reviews_alfaromeo["Vehicle_Title"].str.split()[0][1] + " " + df_reviews_alfaromeo["Vehicle_Title"].str.split()[0][2]
df_reviews_astonmartin["Make"] = df_reviews_astonmartin["Vehicle_Title"].str.split()[0][1] + " " + df_reviews_astonmartin["Vehicle_Title"].str.split()[0][2]
df_reviews_audi["Make"] = df_reviews_audi["Vehicle_Title"].str.split()[0][1]
df_reviews_bentley["Make"] = df_reviews_bentley["Vehicle_Title"].str.split()[0][1]
df_reviews_bmw["Make"] = df_reviews_bmw["Vehicle_Title"].str.split()[0][1]
df_reviews_buick["Make"] = df_reviews_buick["Vehicle_Title"].str.split()[0][1]
df_reviews_cadillac["Make"] = df_reviews_cadillac["Vehicle_Title"].str.split()[0][1]
df_reviews_chevrolet["Make"] = df_reviews_chevrolet["Vehicle_Title"].str.split()[0][1]
df_reviews_chrysler["Make"] = df_reviews_chrysler["Vehicle_Title"].str.split()[0][1]
df_reviews_dodge["Make"] = df_reviews_dodge["Vehicle_Title"].str.split()[0][1]
df_reviews_ferrari["Make"] = df_reviews_ferrari["Vehicle_Title"].str.split()[0][1]
df_reviews_fiat["Make"] = df_reviews_fiat["Vehicle_Title"].str.split()[0][1]
df_reviews_ford["Make"] = df_reviews_ford["Vehicle_Title"].str.split()[0][1]
df_reviews_genesis["Make"] = df_reviews_genesis["Vehicle_Title"].str.split()[0][1]
df_reviews_gmc["Make"] = df_reviews_gmc["Vehicle_Title"].str.split()[0][1]
df_reviews_honda["Make"] = df_reviews_honda["Vehicle_Title"].str.split()[0][1]
df_reviews_hummer["Make"] = df_reviews_hummer["Vehicle_Title"].str.split()[0][1]
df_reviews_hyundai["Make"] = df_reviews_hyundai["Vehicle_Title"].str.split()[0][1]
df_reviews_infiniti["Make"] = df_reviews_infiniti["Vehicle_Title"].str.split()[0][1]
df_reviews_kia["Make"] = df_reviews_kia["Vehicle_Title"].str.split()[0][1]
df_reviews_lamborghini["Make"] = df_reviews_lamborghini["Vehicle_Title"].str.split()[0][1]
df_reviews_land_rover["Make"] = df_reviews_land_rover["Vehicle_Title"].str.split()[0][1] + " " + df_reviews_land_rover["Vehicle_Title"].str.split()[0][2]
df_reviews_lexus["Make"] = df_reviews_lexus["Vehicle_Title"].str.split()[0][1]
df_reviews_lincoln["Make"] = df_reviews_lincoln["Vehicle_Title"].str.split()[0][1]
df_reviews_lotus["Make"] = df_reviews_lotus["Vehicle_Title"].str.split()[0][1]
df_reviews_maserati["Make"] = df_reviews_maserati["Vehicle_Title"].str.split()[0][1]
df_reviews_maybach["Make"] = df_reviews_maybach["Vehicle_Title"].str.split()[0][1]
df_reviews_mazda["Make"] = df_reviews_mazda["Vehicle_Title"].str.split()[0][1]
df_reviews_mclaren["Make"] = df_reviews_mclaren["Vehicle_Title"].str.split()[0][1]
df_reviews_mercedes_benz["Make"] = df_reviews_mercedes_benz["Vehicle_Title"].str.split()[0][1]
df_reviews_mitsubishi["Make"] = df_reviews_mitsubishi["Vehicle_Title"].str.split()[0][1]
df_reviews_nissan["Make"] = df_reviews_nissan["Vehicle_Title"].str.split()[0][1]
df_reviews_pontiac["Make"] = df_reviews_pontiac["Vehicle_Title"].str.split()[0][1]
df_reviews_porsche["Make"] = df_reviews_porsche["Vehicle_Title"].str.split()[0][1]
df_reviews_rolls_royce["Make"] = df_reviews_rolls_royce["Vehicle_Title"].str.split()[0][1]
df_reviews_subaru["Make"] = df_reviews_subaru["Vehicle_Title"].str.split()[0][1]
df_reviews_suzuki["Make"] = df_reviews_suzuki["Vehicle_Title"].str.split()[0][1]
df_reviews_tesla["Make"] = df_reviews_tesla["Vehicle_Title"].str.split()[0][1]
df_reviews_toyota["Make"] = df_reviews_toyota["Vehicle_Title"].str.split()[0][1]
df_reviews_volkswagen["Make"] = df_reviews_volkswagen["Vehicle_Title"].str.split()[0][1]
df_reviews_volvo["Make"] = df_reviews_volvo["Vehicle_Title"].str.split()[0][1]

frames = [
  df_reviews_acura,
  df_reviews_alfaromeo,
  df_reviews_astonmartin,
  df_reviews_audi,
  df_reviews_bentley,
  df_reviews_bmw,
  df_reviews_buick,
  df_reviews_cadillac,
  df_reviews_chevrolet,
  df_reviews_chrysler,
  df_reviews_dodge,
  df_reviews_ferrari,
  df_reviews_fiat,
  df_reviews_ford,
  df_reviews_genesis,
  df_reviews_gmc,
  df_reviews_honda,
  df_reviews_hummer,
  df_reviews_hyundai,
  df_reviews_infiniti,
  df_reviews_kia,
  df_reviews_lamborghini,
  df_reviews_land_rover,
  df_reviews_lexus,
  df_reviews_lincoln,
  df_reviews_lotus,
  df_reviews_maserati,
  df_reviews_maybach,
  df_reviews_mazda,
  df_reviews_mclaren,
  df_reviews_mercedes_benz,
  df_reviews_mitsubishi,
  df_reviews_nissan,
  df_reviews_pontiac,
  df_reviews_porsche,
  df_reviews_rolls_royce,
  df_reviews_subaru,
  df_reviews_suzuki,
  df_reviews_tesla,
  df_reviews_toyota,
  df_reviews_volkswagen,
  df_reviews_volvo
]
df_reviews = pd.concat(frames)
df_reviews.drop("Unnamed: 0", axis=1, inplace=True)
df_reviews = df_reviews[~df_reviews["Review_Title"].isna()]
df_reviews = df_reviews[~df_reviews["Author_Name"].isna()]
df_reviews["Rating\r"] = df_reviews["Rating\r"].fillna(df_reviews["Rating"])
df_reviews.drop("Rating", axis=1, inplace=True)
df_reviews = df_reviews.rename(columns={"Rating\r": "Rating"})
df_reviews = df_reviews.groupby("Author_Name").filter(lambda x : len(x)>19)
df_reviews = df_reviews.reset_index()
df_reviews.drop("index", axis=1, inplace=True)
df_reviews

,Review_Date,Author_Name,Vehicle_Title,Review_Title,Review,Rating,Make
0,on 01/17/17 10:49 AM (PST),Bob,2017 Acura RLX Sedan Technology Package 4dr Se...,Great Car,Traded in a 2012 Acura TL . The 2017 Acura R...,5.000,Acura
1,on 07/31/18 10:58 AM (PDT),David,2018 Acura RLX Hybrid Sport Hybrid SH-AWD 4dr ...,Liked the 2014 model and this is even better,Entertainment system may not be intuitive or ...,5.000,Acura
2,on 02/04/10 09:48 AM (PST),dan,2006 Acura RSX Hatchback 2dr Hatchback (2.0L 4...,No more acuras/hondas for me,I bought this car used only to have problems ...,3.000,Acura
3,on 08/19/08 12:11 PM (PDT),David,2006 Acura RSX Hatchback 2dr Hatchback (2.0L 4...,Great Sports Car,"This car is great, pretty fast for a 2.0L inl...",4.875,Acura
4,on 06/09/08 12:43 PM (PDT),Keith,2006 Acura RSX Hatchback 2dr Hatchback (2.0L 4...,Great first sports car,This car is great for a first sports car. It ...,4.875,Acura
...,...,...,...,...,...,...,...
29726,on 03/10/18 14:40 PM (PST),Jonathan,2009 Volvo C30 Hatchback T5 2dr Hatchback (2.5...,My 3rd Volvo,"Sporty, clean lines, well thought out and fun...",5.000,Volvo
29727,on 03/15/10 02:03 AM (PDT),D,2009 Volvo C30 Hatchback T5 2dr Hatchback (2.5...,Great little car,We bought a C30 on our return to the US after...,4.750,Volvo
29728,on 03/01/10 19:06 PM (PST),Paul,2009 Volvo C30 Hatchback T5 2dr Hatchback (2.5...,"Best in Class, Value and Otherwise","Strangely, this exquisite, sophisticated car ...",4.750,Volvo
29729,on 12/19/09 10:41 AM (PST),Terri,2009 Volvo C30 Hatchback T5 2dr Hatchback (2.5...,Just Right,I literally test drove 12 vehicles and kept c...,4.750,Volvo
29730,on 11/27/09 20:53 PM (PST),kevin,2009 Volvo C30 Hatchback T5 2dr Hatchback (2.5...,Still brings a smile to my face,After researching all small hatchbacks in the...,4.125,Volvo

In [22]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29731 entries, 0 to 29730
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Review_Date    29731 non-null  object
 1   Author_Name    29731 non-null  object
 2   Vehicle_Title  29731 non-null  object
 3   Review_Title   29731 non-null  object
 4   Review         29731 non-null  object
 5   Rating         29731 non-null  float64
 6   Make           29731 non-null  object
dtypes: float64(1), object(6)
memory usage: 1.6+ MB

In [23]:
df_reviews["Author_Name"].value_counts()

Author_Name
Mike        842
John        748
Dave        550
Steve       525
Jim         491
           ...
sean         20
John         20
charles      20
Peggy        20
Allan        20
Name: count, Length: 419, dtype: int64

In [24]:
df_reviews.to_csv("../datasets/reviews/reviews_dataset.csv", sep=",")